name: Fetch Medium Posts

on:
  schedule:
    - cron: "0 */6 * * *"        # every 6 hours
  workflow_dispatch:              # allow manual runs
  push:
    branches: [ main ]            # also run on pushes to main

permissions:
  contents: write                 # allow the bot to push back to the repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser beautifulsoup4

      - name: Build Medium JSON
        run: |
          python scripts/build_medium.py

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Commit only if there are changes
      - name: Commit changes (if any)
        run: |
          git add static/data/medium_posts.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update Medium posts"
            git push origin HEAD:main
          fi
